FROM node:16

WORKDIR /opt

COPY . .
RUN npm install
RUN npm i -g pm2 gulp

RUN rm /opt/gulp/res/js/socket.io.js

COPY ./docker/jschan/secrets.js ./configs/secrets.js

#i fucking hate docker
ENV MONGO_USERNAME jschan
ENV MONGO_PASSWORD changeme
ENV REDIS_PASSWORD changeme

CMD ["/bin/sh", "-c", "gulp reset; gulp"]
